### ISSUE TITLE
A question about matrix X in Section 4.

### ISSUE THREAD

**Issue by DreamMr** [bronyayang/Law_of_Vision_Representation_in_MLLMs#1]
Hi~ Nice work! I have read your paper and believe that the work is of great significance. While reading, I had a question regarding Section 4 AC POLICY, where the matrix X has dimensions of k*6. I understand that k represents the k vision representations, but what does the 6 mean? Why is it 6?

**Comment by pansanity666** [comment]
Same here.

**Comment by bronyayang** [comment]
Hi,

Thanks for your interest in our work!

k vision representation should have A and C scores. This is 2 terms, [A C] to fit the linear regression if no transformation. However, AC score is a second degree polynomial transformation on A and C score, making a 6 terms vector to fit. In vectorized form, it’s [1 A A^2 A•C C C^2].

**Comment by DreamMr** [comment]
Thanks for your answer.

**Comment by pansanity666** [comment]
Interesting. Thanks!

**Comment by daiqing98** [comment]
> Hi,
> 
> Thanks for your interest in our work!
> 
> k vision representation should have A and C scores. This is 2 terms, [A C] to fit the linear regression if no transformation. However, AC score is a second degree polynomial transformation on A and C score, making a 6 terms vector to fit. In vectorized form, it’s [1 A A^2 A•C C C^2].

Hi @bronyayang , thanks for your work! I hava a simple question. Why CLIP vision embeddings can be used as the reference? Is is because that CLIP is assumed to be good enough in terms of alignment given its image-text contrastive pre- training?

**Comment by bronyayang** [comment]
> > Hi,
> > Thanks for your interest in our work!
> > k vision representation should have A and C scores. This is 2 terms, [A C] to fit the linear regression if no transformation. However, AC score is a second degree polynomial transformation on A and C score, making a 6 terms vector to fit. In vectorized form, it’s [1 A A^2 A•C C C^2].
> 
> Hi @bronyayang , thanks for your work! I hava a simple question. Why CLIP vision embeddings can be used as the reference? Is is because that CLIP is assumed to be good enough in terms of alignment given its image-text contrastive pre- training?

Yes! This is the assumption. The CLIP objective is to align to the text distribution and disregard everything else.
