### ISSUE TITLE
Questions about A, C scores

### ISSUE THREAD

**Issue by WYY220062** [bronyayang/Law_of_Vision_Representation_in_MLLMs#5]
Hi,
Thank you for this great work!
After reading the paper, I am a bit confused about the A, C scores calculation.
Can you show a concrete numerical example?
Thanks a lot!

**Comment by bronyayang** [comment]
Hi, 

Thanks for your interest!
We believe the best example and best way to understand A,C score would be follow the code and calculate the AC score of normal LLaVA 1.5.
You can also look over the code.
Let me know if you have any specific question on AC score calculation!
