### ISSUE TITLE
Question about equation 3, C Score calculation

### ISSUE THREAD

**Issue by tangli-udel** [bronyayang/Law_of_Vision_Representation_in_MLLMs#8]
Hi,

Thank you for the great work!

I'm getting confused about the notations of equation 3. Based on my understanding, we have a pair of images, source $s$ and target $t$.

"Given ground truth key points { $p^s_1, . . . , p^s_m$ }, we obtain the predicted key points { $p^t_1, . . . , p^t_m$ } using the features."
1. How are the "predicted key points" predicted? Do we use the similarity between source and target image features to predict it?
2. If this is the case, shouldn't the ground truth key points also be on the target image? Like the ground truth key points are { $p^t_1, . . . , p^t_m$ } and the predicted key points are { $\hat{p^t_1}, . . . , \hat{p^t_m}$ }.
3. Based on my understanding, it might be a $j=0$ under the summation. Then what is a $p^s_j - p^t_j$? Is it a distance metric?
4. Does equation 3 calculate the C Score for just one pair of images? We should do this for all pairs of images in the annotated dataset?

**Comment by waltonfuture** [comment]
Same question. Quite confused about the C score. I have also carefully read Zhihu but cannot find the answer

**Comment by bronyayang** [comment]
Hi,

Correspondence score is the standard calculation method from computer vision. We do not make any modification from their common evaluations. Therefore, we did not teach correspondence in our paper or post. If you are interested in reading more about how to calculate correspondence for a certain feature extractor, welcome to read our code or [more papers](https://telling-left-from-right.github.io) on correspondence. Thanks!
