### ISSUE TITLE
Question about A score

### ISSUE THREAD

**Issue by waltonfuture** [bronyayang/Law_of_Vision_Representation_in_MLLMs#9]
In the paper, it’s written that we calculate the maximum cosine similarity between vector pairs from the CLIP embedding and target vision representation embedding. How can this indicate cross-modal alignment since we do not use any textual information from LLM. Look forward to further explanation. Thanks

**Comment by bronyayang** [comment]
Hi,

I think this [issue](https://github.com/bronyayang/Law_of_Vision_Representation_in_MLLMs/issues/1#issuecomment-2325433490) can answer your question. Thanks!
